### ISSUE TITLE
Long notes textures show incorrectly

### ISSUE THREAD

**Issue by SayakaIsBaka** [Stepland/F.E.I.S.#1]
*Versions: 1.0.1 and current master branch*
*Tested on Windows and Linux (Arch)*

The textures for long notes show incorrectly in the versions mentioned above, as shown on this picture (Windows, version 1.0.1)
![](https://sayakaisbaka.s-ul.eu/KlGpDrWx)

**Comment by Stepland** [comment]
Well that's weird for sure, I'm guessing it's related to the lazy way I implemented long notes, that issue will have to wait until I refactor the whole thing

**Comment by Stepland** [comment]
3070b7c760005240972958418059f047e9f312d2 contains a fix attempt, how does it look ?

**Comment by Stepland** [comment]
How does it look now ?

**Comment by SayakaIsBaka** [comment]
Looks perfect now, thanks!
