### ISSUE TITLE
Crash when trying to put notes too early in the chart

### ISSUE THREAD

**Issue by SayakaIsBaka** [Stepland/F.E.I.S.#2]
*Versions: 1.0.1 and current master branch*
*Tested on Windows and Linux (Arch)*

The program crashes when trying to put a note too early in the song, with the following message in the log: `what(): Tried creating a note with negative timing : -200` (the value may change depending on where the note was being placed)

Steps to reproduce:
- Create a new chart with all default settings (although it also happened to me with custom timing settings)
- Try placing a note in the first two beats of the chart (in measure 0)

It also looks like this only occurs within the first two beats of the chart (trying to place a note on and after the 3rd beat works)

**Comment by Stepland** [comment]
I think I found the issue, is it working now ?

**Comment by SayakaIsBaka** [comment]
Yeah it's working, thank you!

**Comment by SayakaIsBaka** [comment]
Reopening because I just noticed the issue still occurs when trying to place a long note, sorry for not noticing before

**Comment by SayakaIsBaka** [comment]
Looks like it has been fixed, thanks!
